name: release

on:
  push:
    branches:
      - main
      - release-**
  pull_request:
    types:
      - synchronize
      - opened
      - labeled

permissions:
  contents: write # so it can comment

defaults:
  run:
    shell: bash --noprofile --norc -x -eo pipefail {0}

jobs:
  check:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'build-release') ||
      (github.event_name == 'pull_request' && github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'build-release'))
    outputs:
      do: ${{ steps.check.outputs.do }}
    steps:
      - id: check
        name: check if need to run the release build
        run: |
          cat $GITHUB_EVENT_PATH
          echo "do=true" >> $GITHUB_OUTPUT

  default:
    needs: check
    if: needs.check.outputs.do == 'true'
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        ubuntu_version: [latest, 20.04]
    uses: ./.github/workflows/build-test.yml
    with:
      ubuntu_version: ${{ matrix.ubuntu_version }}
      compiler: ${{ matrix.compiler }}
      name: "ubuntu.${{ matrix.ubuntu_version }}-${{ matrix.compiler }}-latest"
      cache_build: ${{ matrix.compiler == 'gcc' && matrix.ubuntu_version == 'latest' }}

  more-server-versions:
    needs: [check, default]
    if: needs.check.outputs.do == 'true'
    strategy:
      fail-fast: false
      matrix:
        server_version: [main, dev, v2.9.11]
    uses: ./.github/workflows/build-test.yml
    with:
      server_version: ${{ matrix.server_version }}
      name: "ubuntu.latest-gcc-${{ matrix.server_version }}"
      cache_build: true

  TLS-OFF:
    needs: [check, default]
    if: needs.check.outputs.do == 'true'
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    uses: ./.github/workflows/build-test.yml
    with:
      tls: OFF
      name: "ubuntu.latest-${{ matrix.compiler }}-latest: no TLS"

  older-cc:
    needs: [check, default]
    if: needs.check.outputs.do == 'true'
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc-7, gcc-8, clang-8]
    uses: ./.github/workflows/build-test.yml
    with:
      ubuntu_version: 20.04
      compiler: ${{ matrix.compiler }}
      quick_test: ON
      name: "ubuntu.20.04-${{ matrix.compiler }}-quick-check"

  no-streaming:
    needs: [check, default]
    if: needs.check.outputs.do == 'true'
    uses: ./.github/workflows/build-test.yml
    with:
      streaming: OFF
      name: "ubuntu.latest-gcc-latest: no streaming"
