name: "Build & Tests"
on:
  push:
    branches:
      - main
      - release_*

permissions:
  contents: write # required by build-test to comment on coverage but not used here.

defaults:
  run:
    shell: bash --noprofile --norc -x -eo pipefail {0}

jobs:
  server-versions:
    strategy:
      fail-fast: false
      matrix:
        server_version: [latest, v2.11.10]
    uses: ./.github/workflows/build-test.yml
    name: "Other servers"
    with:
      server_version: ${{ matrix.server_version }}

  TLS-OFF:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    uses: ./.github/workflows/build-test.yml
    name: "No TLS"
    with:
      tls: OFF

  no-streaming:
    uses: ./.github/workflows/build-test.yml
    name: "No Streaming"
    with:
      streaming: OFF

  coverage:
    name: "Coverage"
    uses: ./.github/workflows/build-test.yml
    with:
      coverage: ON
      server_version: main
      type: Debug
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
